# Generated by Django 4.2.14 on 2024-07-30 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=128)),
                ("hotelClass", models.FloatField(blank=True, null=True)),
                ("image", models.URLField(blank=True, max_length=1024, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{8,15}$"
                            )
                        ],
                    ),
                ),
                ("priceLevel", models.CharField(max_length=32)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("subcategories", models.CharField(max_length=64)),
                ("website", models.URLField(max_length=1028)),
                ("amenities", models.CharField(max_length=128)),
            ],
        ),
    ]
