# Generated by Django 5.0.7 on 2024-08-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0007_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourism',
            name='Dietaryrestrictions',
        ),
        migrations.RemoveField(
            model_name='tourism',
            name='cuisine',
        ),
    ]
