# Generated by Django 5.0.7 on 2024-08-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Circuitrecommender', '0009_tourism_city_alter_tourism_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='City',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Country',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
